version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: orders_postgres
    environment:
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderuser -d ordersdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats-streaming:
    image: nats-streaming:latest
    container_name: orders_nats
    command: ["-p", "4222", "-m", "8222", "--store", "file", "--dir", "datastore"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/datastore

volumes:
  postgres_data:
  nats_data:
